CREATE OR REPLACE PROCEDURE CALCULACAMINHOS AS 
 ORIGEM VARCHAR(1); 
 ELEM VARCHAR(50);
 VAR NUMBER(15);
 CUSTO NUMBER(15);
 BEGIN
 LIMPAFILA;
 ORIGEM := 'A';
 INSEREFILA (ORIGEM);
   WHILE NELEMENTOSFILA > 0 LOOP
    ELEM := RETIRAFILA;
    FOR CONL IN (SELECT * FROM CONEXAO WHERE ORIGEM = ELEM) LOOP
        SELECT COUNT(*) into VAR FROM CAMINHOS WHERE SUBSTR(CAMINHOS.CAMINHO, length(CAMINHOS.CAMINHO), length(CAMINHOS.CAMINHO)) = ELEM;
        IF VAR > 0 THEN
          FOR CAMI IN (SELECT * FROM CAMINHOS where SUBSTR(CAMINHOS.CAMINHO, length(CAMINHOS.CAMINHO), length(CAMINHOS.CAMINHO)) = ELEM) LOOP
            INSERT INTO CAMINHOS VALUES(CAMI.CAMINHO || CONL.ORIGEM, CAMI.CUSTOCAMINHO + CONL.CUSTO);
          END LOOP;
        ELSE
          INSERT INTO CAMINHOS VALUES(CONL.ORIGEM||CONL.DESTINO, CONL.CUSTO);
        END IF;
      INSEREFILA(CONL.DESTINO);
    END LOOP;
   END LOOP; 
END CALCULACAMINHOS;
